# Generated by Django 6.0.3 on 2026-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_blog', '0004_category_slug_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
